"""on delete cascade

Revision ID: bcbf74a6d800
Revises: a97bebe3a2e7
Create Date: 2025-12-16 10:43:17.924749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcbf74a6d800'
down_revision: Union[str, Sequence[str], None] = 'a97bebe3a2e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('employee_company_id_fkey'), 'employee', type_='foreignkey')
    op.create_foreign_key(None, 'employee', 'company', ['company_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('project_company_id_fkey'), 'project', type_='foreignkey')
    op.create_foreign_key(None, 'project', 'company', ['company_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project', type_='foreignkey')
    op.create_foreign_key(op.f('project_company_id_fkey'), 'project', 'company', ['company_id'], ['id'])
    op.drop_constraint(None, 'employee', type_='foreignkey')
    op.create_foreign_key(op.f('employee_company_id_fkey'), 'employee', 'company', ['company_id'], ['id'])
    # ### end Alembic commands ###
