CREATE TABLE "User" (
    UserID SERIAL PRIMARY KEY,
    FullName VARCHAR(100) NOT NULL,
    Email VARCHAR(100) UNIQUE NOT NULL,
    PasswordHash VARCHAR(255) NOT NULL
);

CREATE TABLE Team (
    TeamID SERIAL PRIMARY KEY,
    TeamName VARCHAR(100) NOT NULL,
    Description TEXT
);

CREATE TABLE Project (
    ProjectID SERIAL PRIMARY KEY,
    ProjectName VARCHAR(100) NOT NULL,
    Description TEXT,
    StartDate DATE NOT NULL,
    EndDate DATE,
    TeamID INT REFERENCES Team(TeamID) ON DELETE SET NULL
);

CREATE TABLE Board (
    BoardID SERIAL PRIMARY KEY,
    BoardName VARCHAR(100) NOT NULL,
    ProjectID INT REFERENCES Project(ProjectID) ON DELETE CASCADE
);

CREATE TABLE Task (
    TaskID SERIAL PRIMARY KEY,
    Title VARCHAR(150) NOT NULL,
    Description TEXT,
    Status VARCHAR(50) DEFAULT 'To Do',
    Priority VARCHAR(20) CHECK (Priority IN ('Low','Medium','High')),
    DueDate DATE,
    BoardID INT REFERENCES Board(BoardID) ON DELETE CASCADE
);

CREATE TABLE Comment (
    CommentID SERIAL PRIMARY KEY,
    Content TEXT NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UserID INT REFERENCES "User"(UserID) ON DELETE CASCADE,
    TaskID INT REFERENCES Task(TaskID) ON DELETE CASCADE
);

CREATE TABLE Tag (
    TagID SERIAL PRIMARY KEY,
    TagName VARCHAR(50) NOT NULL,
    Color VARCHAR(20)
);

CREATE TABLE Task_Assignee (
    UserID INT REFERENCES "User"(UserID) ON DELETE CASCADE,
    TaskID INT REFERENCES Task(TaskID) ON DELETE CASCADE,
    PRIMARY KEY (UserID, TaskID)
);

CREATE TABLE Task_Tag (
    TaskID INT REFERENCES Task(TaskID) ON DELETE CASCADE,
    TagID INT REFERENCES Tag(TagID) ON DELETE CASCADE,
    PRIMARY KEY (TaskID, TagID)
);

CREATE TABLE Project_User (
    ProjectID INT REFERENCES Project(ProjectID) ON DELETE CASCADE,
    UserID INT REFERENCES "User"(UserID) ON DELETE CASCADE,
    Role VARCHAR(50) NOT NULL,
    PRIMARY KEY (ProjectID, UserID)
);

CREATE TABLE Team_User (
    TeamID INT REFERENCES Team(TeamID) ON DELETE CASCADE,
    UserID INT REFERENCES "User"(UserID) ON DELETE CASCADE,
    Role VARCHAR(50) NOT NULL, 
    PRIMARY KEY (TeamID, UserID)
);